//! Generating a config for, and launching, a bundled `rustical` CalDAV server. rustical is
//! the local hub that serves the vault to a phone (DAVx5 via WebDAV-Push). We generate its
//! config and spawn the binary if it is on `PATH`.

use std::path::{Path, PathBuf};
use std::process::{Child, Command};

use mgmt_core::{Error, Result};

/// Settings for the bundled rustical instance.
#[derive(Debug, Clone)]
pub struct RusticalConfig {
    pub host: String,
    pub port: u16,
    pub data_dir: PathBuf,
}

impl RusticalConfig {
    pub fn new(data_dir: impl Into<PathBuf>) -> Self {
        RusticalConfig {
            host: "127.0.0.1".to_string(),
            port: 4000,
            data_dir: data_dir.into(),
        }
    }

    /// Render a best-effort `rustical.toml`. rustical stores everything in one SQLite file;
    /// users can hand-tune the generated file (it lives next to the data dir).
    pub fn to_toml(&self) -> String {
        let db = self.data_dir.join("rustical.db");
        format!(
            "# Generated by mgmt — edit to taste.\n\
             [http]\n\
             host = \"{host}\"\n\
             port = {port}\n\n\
             [frontend]\n\
             enabled = true\n\n\
             [data]\n\
             type = \"sqlite\"\n\
             path = {db:?}\n",
            host = self.host,
            port = self.port,
            db = db,
        )
    }

    /// Write the config to `path`, creating parent directories.
    pub fn write(&self, path: &Path) -> Result<()> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(path, self.to_toml())?;
        Ok(())
    }

    /// Spawn `rustical --config <path>`. Returns a handle the caller supervises, or an error
    /// if the binary is not installed.
    pub fn spawn(&self, config_path: &Path) -> Result<Child> {
        Command::new("rustical")
            .arg("--config")
            .arg(config_path)
            .spawn()
            .map_err(|e| match e.kind() {
                std::io::ErrorKind::NotFound => {
                    Error::NotFound("rustical not found on PATH — install it to serve to your phone".into())
                }
                _ => Error::Io(e),
            })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn toml_contains_port_and_db_path() {
        let cfg = RusticalConfig::new("/data/mgmt");
        let toml = cfg.to_toml();
        assert!(toml.contains("port = 4000"));
        assert!(toml.contains("rustical.db"));
        assert!(toml.contains("type = \"sqlite\""));
    }

    #[test]
    fn write_creates_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("etc").join("rustical.toml");
        RusticalConfig::new(dir.path()).write(&path).unwrap();
        assert!(path.exists());
        assert!(std::fs::read_to_string(&path).unwrap().contains("[http]"));
    }
}
